### ISSUE TITLE
Run wheel build in parallel

### ISSUE THREAD

**Issue by ikanago** [qulacs/qulacs#393]
I suggest running wheel build in parallel by using [`jobs.<job_id>.strategy.matrix`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix).
```yaml
jobs
  wheel-build:
    name: Python wheel build
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' || github.event.review.state == 'approved' }}
    strategy:
      matrix:
        python-version: ["3.7.5"]
        os: ["ubuntu-20.04", "windows-2019", "macos-11"]
        target: ["cp38", "cp39", "cp310"]
```
