### ISSUE TITLE
Integrate doc/requirements.txt into pyproject.toml

### ISSUE THREAD

**Issue by Hiroya-W** [qulacs/qulacs#520]
ref: https://docs.readthedocs.io/en/stable/config-file/v2.html#packages

If we write a config file in the root directory named `.readthedocs.yaml` with the following contents, we can run the equivalent of the following command.

```yaml
version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
```

```
pip install .[doc]
